# Generated by Django 2.2.5 on 2019-09-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_auto_20190626_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetBuoy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dataset',),
        ),
    ]
